name: ttcs
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.0
  firebase_auth: ^4.16.0
  google_sign_in: ^6.1.0
  flutter_facebook_auth: ^7.0.1
  cloud_firestore: ^4.13.0
  file_picker: ^8.0.6
  image_picker: ^1.0.7
  intl: ^0.18.0
  dotted_border: ^2.1.0
  provider: ^6.0.0
  rxdart: ^0.27.0
  permission_handler: ^11.3.0
  path_provider: ^2.1.3  # Thêm nếu sử dụng
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  plugin:
    platforms:
      linux:
        pluginClass: None
      macos:
        pluginClass: None
      windows:
        pluginClass: None